import tkinter as tk
import subprocess

def find_lesson_for_kanji(kanji):
    kanji_to_lesson = {
        '一' : 3,
        '二' : 3,
        '三' : 3,
        '四' : 3,
        '五' : 3,
        '六' : 3,
        '七' : 3,
        '八' : 3,
        '九' : 3,
        '十' : 3,
        '百' : 3,
        '千' : 3,
        '万' : 3,
        '円' : 3,
        '時' : 3,
        '日' : 4, 
        '本' : 4, 
        '人' : 4, 
        '月' : 4, 
        '火' : 4, 
        '水' : 4, 
        '木' : 4, 
        '金' : 4, 
        '土' : 4, 
        '曜' : 4, 
        '上' : 4, 
        '下' : 4, 
        '中' : 4, 
        '半' : 4, 
        '山' : 5,
        '川' : 5,
        '元' : 5,
        '気' : 5,
        '天' : 5,
        '私' : 5,
        '今' : 5,
        '田' : 5,
        '女' : 5,
        '男' : 5,
        '見' : 5,
        '行' : 5,
        '食' : 5,
        '飲' : 5,
        '東' : 6,
        '西' : 6,
        '南' : 6,
        '北' : 6,
        '口' : 6,
        '出' : 6,
        '右' : 6,
        '左' : 6,
        '分' : 6,
        '先' : 6,
        '生' : 6,
        '大' : 6,
        '学' : 6,
        '外' : 6,
        '国' : 6,
        '京' : 7,
        '子' : 7,
        '小' : 7,
        '会' : 7,
        '社' : 7,
        '父' : 7,
        '母' : 7,
        '高' : 7,
        '校' : 7,
        '毎' : 7,
        '語' : 7,
        '文' : 7,
        '帰' : 7,
        '入' : 7,
        '員' : 8,
        '新' : 8,
        '聞' : 8,
        '作' : 8,
        '仕' : 8,
        '事' : 8,
        '電' : 8,
        '車' : 8,
        '休' : 8,
        '言' : 8,
        '読' : 8,
        '思' : 8,
        '次' : 8,
        '何' : 8,
        '午' : 9,
        '後' : 9,
        '前' : 9,
        '名' : 9,
        '白' : 9,
        '雨' : 9,
        '書' : 9,
        '友' : 9,
        '間' : 9,
        '家' : 9,
        '話' : 9,
        '少' : 9,
        '古' : 9,
        '知' : 9,
        '来' : 9,
        '住' : 10,
        '正' : 10,
        '年' : 10,
        '売' : 10,
        '買' : 10,
        '町' : 10,
        '長' : 10,
        '道' : 10,
        '雪' : 10,
        '立' : 10,
        '自' : 10,
        '夜' : 10,
        '朝' : 10,
        '持' : 10,
        '手' : 11,
        '紙' : 11,
        '好' : 11,
        '近' : 11,
        '明' : 11,
        '病' : 11,
        '院' : 11,
        '映' : 11,
        '画' : 11,
        '歌' : 11,
        '市' : 11,
        '所' : 11,
        '勉' : 11,
        '強' : 11,
        '有' : 11,
        '旅' : 11,
        '昔' : 12,
        '神' : 12,
        '早' : 12,
        '起' : 12,
        '牛' : 12,
        '使' : 12,
        '働' : 12,
        '連' : 12,
        '別' : 12,
        '度' : 12,
        '赤' : 12,
        '青' : 12,
        '色' : 12,
        '物' : 13,
        '鳥' : 13,
        '料' : 13,
        '理' : 13,
        '特' : 13,
        '安' : 13,
        '飯' : 13,
        '肉' : 13,
        '悪' : 13,
        '体' : 13,
        '空' : 13,
        '港' : 13,
        '着' : 13,
        '同' : 13,
        '海' : 13,
        '昼' : 13,
        '彼' : 14,
        '代' : 14,
        '留' : 14,
        '族' : 14,
        '親' : 14,
        '切' : 14,
        '英' : 14,
        '店' : 14,
        '去' : 14,
        '急' : 14,
        '乗' : 14,
        '当' : 14,
        '音' : 14,
        '楽' : 14,
        '医' : 14,
        '者' : 14,
        '死' : 15,
        '意' : 15,
        '味' : 15,
        '注' : 15,
        '夏' : 15,
        '魚' : 15,
        '寺' : 15,
        '広' : 15,
        '転' : 15,
        '借' : 15,
        '走' : 15,
        '建' : 15,
        '地' : 15,
        '場' : 15,
        '足' : 15,
        '通' : 15,
        '供' : 16,
        '世' : 16,
        '界' : 16,
        '全' : 16,
        '部' : 16,
        '始' : 16,
        '週' : 16,
        '以' : 16,
        '考' : 16,
        '開' : 16,
        '屋' : 16,
        '方' : 16,
        '運' : 16,
        '動' : 16,
        '教' : 16,
        '室' : 16
    }
    return kanji_to_lesson.get(kanji, "Not found")

def display_kanji():
    kanji = kanji_entry.get()
    lesson = find_lesson_for_kanji(kanji)
    result_label.config(text=f"The kanji '{kanji}' was first introduced in Lesson {lesson}.")

# Create the main application window with a width of 400 pixels
app = tk.Tk()
app.title("Kanji Lesson Finder")
app.geometry("300x100")  # Set the width and height
app.resizable(width=False, height=False)

# Create a label and entry widget for entering kanji
kanji_label = tk.Label(app, text="Enter a kanji character:")
kanji_label.pack()

kanji_entry = tk.Entry(app)
kanji_entry.pack()

# Create a button to find the lesson for the entered kanji
find_button = tk.Button(app, text="Find Lesson", command=display_kanji)
find_button.pack()

# Create a label to display the result
result_label = tk.Label(app, text="")
result_label.pack()

# Start the GUI main loop
app.mainloop()